config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :pins
  
  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates :image, presence: true
	validates :description, length: { maximum: 500 }, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :pins

	validates :name, length: { maximum: 30 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
     render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this Pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# The resource defined below is used to handle the login box in the header.
	# It should be removed once the render block in _header.html.erb is removed
	def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_center_content.html.erb
<div class="panel panel-default">
	<div class="panel-body center">
		<%= link_to pins_path, class: "btn btn-danger" do %>
		<span class="glyphicon glyphicon-step-backward"></span>Back
		<% end %>
		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin), class: "btn btn-danger" do %>
			<span class="glyphicon glyphicon-edit"></span>Edit
			<% end %>
		<% end %>
	</div>
</div>

<div class="panel panel-default">
	<div id="image-no-pad">
		<div class="panel-heading center">
			<%= image_tag @pin.image.url %>
		</div>
	</div>

	<div class="panel-body">
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>
		<p><%= @pin.description %></p>
	</div>

	<div class="panel-footer">
	  <div class="actions">
	      <p>Comment Box goes here</p>
	  </div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <a href="#"><img src="http://www.kissingerassoc.com/images/1.gif"/></a>
      	<div class="small center-to-left ">&copy; 2015 Social Network Inc.
        </div>
     	</div>

      <div class="col-sm-6">
         	<div class="text-center">
            <ul class="list-inline">
              <li><%= link_to "Home", root_path %></li> | <li><%= link_to "About Social Network", about_path %></li> | 
              <li><%= link_to "Terms of Use", "#" %></li> | <li><%= link_to "Privacy Policy", "#" %></li>
            </ul>
         	</div>
      </div>

      <div class="col-sm-3">
          <div class="center-to-right">
  					<p>social icons</p>
       		</div>
   		</div>
   	</div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Social Network", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus" aria-hidden
            ="true"></span>Add New
            <% end %>
          </li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
            <span class="glyphicon glyphicon-log-out"></span>Log Out
            <% end %>
          </li>
        <% else %>
        <%= render 'layouts/header_sign_in' %>
        <!-- The render block above replaced the log-in function below
        It should be removed once the resources defined in application_helper.rb is removed --> 

          <!-- <li><%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span>Log In
            <% end %>
          </li> -->
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_header_sign_in.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-md-push-5">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true %>
        <%= link_to "Forgot your password?", new_password_path(resource_name) %>
      </div>
      <div class="col-md-3 col-md-push-5">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "off" %>

        <% if devise_mapping.rememberable? -%>
          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        <% end -%>
      </div>

      <div class="pull-right">
        <div class="actions">
          <%= f.submit "Log in", class: "btn btn-primary" %>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/layouts/_left_sidebar_home.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h5>Sort by:</h5>
	</div>

	<div class="panel-body">
		<ul class="nav nav-pills nav-stacked">
		  <li role="presentation" class="active"><a href="#">hot</a></li>
		  <li role="presentation"><a href="#">new</a></li>
		  <li role="presentation"><a href="#">Random</a></li>
		  <li role="presentation"><a href="#">Favorite</a></li>
		  <li role="presentation"><a href="#">Most commented</a></li>
		</ul>
	</div>
</div>

app/views/layouts/_main_content_menu.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to "Home", root_path, class: "active", role: "presentation" %></li>
  <li><%= link_to "Status", statuses_path, role: "presentation" %></li>
  <li role="presentation"><a href="#">Images</a></li>
  <li role="presentation"><a href="#">Videos</a></li>
  <li role="presentation"><a href="#">Links</a></li>
  <li role="presentation"><a href="#">Dating</a></li>
  <li role="presentation"><a href="#">Forum</a></li>
</ul>

app/views/layouts/_right_sidebar_permanent.html.erb
<div class="panel panel-default">
	<div class="panel-body center">
		<%= link_to 'Back', pins_path, class: "btn btn-danger" %>
	</div>
</div>

<div class="panel panel-default">
	<div id="image-no-pad">
		<div class="panel-heading center">
			<%= image_tag @pin.image.url %>
		</div>
	</div>
	
	<div class="panel-body">
		<p><strong><%= @pin.user.name if @pin.user %></strong></p>
		<p><%= @pin.description %></p>
		<% if @pin.user == current_user %>
			<%= link_to 'Edit', edit_pin_path(@pin) %>
		<% end %>
	</div>
	
	<div class="panel-footer">
	  <div class="actions">
	      <p>Comment Box goes here</p>
	  </div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Social Network</title>
		<link type="text/css" rel="stylesheet" href="normalize.css" />
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>

		<div class="container">
			<%= render 'layouts/header' %>
			<%= render 'pages/top_users' if user_signed_in? %>
			<%= render 'pages/home' unless user_signed_in? %>
				<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
				<% end %>
			<%= yield %>
		</div>

	</body>

		<%= render 'layouts/footer' %>
	
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<div class="jumbo-pad">
		<h1>Welcome to Social Network</h1>
		<p>A photo sharing Application</p>
		<p>
			<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-sm" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-sm" %>
		</p>
	</div>
</div>

app/views/pages/_top_users.html.erb
<div class="jumbotron center top-users">
	<h3>Featured Posts</h3>
	<img data-src="holder.js/140x140" class="img-circle" alt="140x140" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA0Njg3NSIgeT0iNzAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MTBwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj4xNDB4MTQwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true" style="width: 100px; height: 100px;">
	<img data-src="holder.js/140x140" class="img-circle" alt="140x140" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA0Njg3NSIgeT0iNzAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MTBwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj4xNDB4MTQwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true" style="width: 100px; height: 100px;">
	<img data-src="holder.js/140x140" class="img-circle" alt="140x140" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA0Njg3NSIgeT0iNzAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MTBwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj4xNDB4MTQwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true" style="width: 100px; height: 100px;">
	<img data-src="holder.js/140x140" class="img-circle" alt="140x140" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgdmlld0JveD0iMCAwIDE0MCAxNDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxkZWZzLz48cmVjdCB3aWR0aD0iMTQwIiBoZWlnaHQ9IjE0MCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjQ0LjA0Njg3NSIgeT0iNzAiIHN0eWxlPSJmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MTBwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj4xNDB4MTQwPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true" style="width: 100px; height: 100px;">
</div>

app/views/pages/about.html.erb
<div class="panel panel-danger center">
	<div class="panel-heading">
		<h1>About Us</h1>
	</div>
	<div class="panel-body">
		<p>This project is based on my first photo app sharing</p>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Pinteresting</h1>
	<p>A photo sharing Application</p>
	<% if user_signed_in? %>
		# do something
	<% else %>
		<p>
			<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-sm" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-sm" %>
		</p>
	<% end %>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group",>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-danger">
	<div class="panel-heading">
		<h1>Editing Pin</h1>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'View Pin', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<% if user_signed_in? %>
<%= render 'layouts/main_content_menu' %>

<div class="row">

  <div class="col-md-2 left-sidebar">
    <%= render 'layouts/left_sidebar_home' if user_signed_in? %>
  </div>
  <div class="sep pull-left" style="height: 610px;">
  </div>
  <div class="col-md-6">
    <% @pins.each do |pin| %>
      <div class="box panel panel-default">
        
        <div class="panel-heading">
          <p><strong><%= pin.user.name if pin.user %></strong>
          </p>
          <%= time_ago_in_words pin.created_at %> ago
        </div>

        <div class="panel-body">
          <p><%= pin.description %></p>
        </div>

        <%= link_to image_tag(pin.image.url), pin %>

        <% if pin.user == current_user %>
          <div class="panel-footer">
            <div class="actions">
              <%= link_to 'Edit', edit_pin_path(pin) %>
              <%= link_to 'Delete', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <% end %>
          
        <div id="comment-area">
          <div class="panel-body">
            <p>User's Stats goes here </p>
          </div>
        </div>

      </div>

    <% end %>

    <div class="center">
      <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>
<% end %>

app/views/pins/new.html.erb
<div class="panel panel-danger">
	<div class="panel-heading">
		<h1>New Pin</h1>
	</div>

	<div class="panel-body">
		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<%= render 'layouts/main_content_menu' if user_signed_in? %>
<div id="single-pin">

	<div class="row">
		<div id="center-content">
			<div class="col-md-6 col-md-offset-3">

				<%= render 'layouts/center_content' %>
			</div>
		</div>
	
		<div id="right_sidebar">
			<div class="col-md-3 col-md-offset-0">	
				<%= render 'layouts/right_sidebar_permanent' %>
			</div>
		</div>

	</div>
</div>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<% if user_signed_in? %>
<%= render 'layouts/main_content_menu' %>

<%= link_to "New Status", new_status_path %>

    <textarea class="form-control" rows="3" placeholder="Textarea"></textarea>

<% @statuses.each do |status| %>
  <div class="panel panel-default">
    <div class="status">
      <strong><%= status.name %></strong>
      <p><%= status.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
        <span class="admin">
          | <%= link_to "Edit", edit_status_path(status) %> | 
          <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure you want to delete this status?" } %>
        </span>
      </div>
    </div>
  </div>
<% end %>

<% end %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>